---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-pdf-secrets
  namespace: prod
spec:
  encryptedData:
    ADMIN_SECRET_KEY: AgAk+goTMD7xeP1iQMQduA5WKv1uAvtm9IOd8I39M1wLli7+/2c4ffTPrJbjjDSta5YkGHOZNSvjgW6a9ixclmGT1kodKFehF9/UkwvssqLw7xlcPq7lnrm3MWo/e0x0MpmagxFFaPccyv1wbseLZLWyI88pSFz8YlOODErJ3RoDrEp20nlPdVxrtsA1SprgOs8o9AZgp7kGGGmLAarXnPjShGiHgOtz1HGyS4tUcKiEkDjcTlMMQQ9qLk2maLFCtp5Aox+Kuujj3jIS46fGVezAbJExJdWCaf1De4cnOaB02ZliaSnW1dsPeUAwxmr0spd315KXh2nIAkELxwCpNxNA8QhWkNMHFVjcmIFdwXU3FU3S6lmjcoEr0LdORdG2SUMo1T4pPhF59vIqettya+FVYzcKJDNPr5Mupltvsl4cWOB9GsaNn31zJ+ZluBes3vMSSm4h8I8x5aK5JrTVBoYepp3qlKPHOxpEZFOOg0aXQKzRvpeBJCaWherjO60SHJqGLAuymk0e4qfaRJ6c5f6k7edCH8zZOofqMFtwoxK7x11z1ifRwjv9SQNhVhxrWalKaxKt7L9pTfCuDA+5KdZgmEeg4Ti1ZV3To0VIsAZOW2FPlWGm2nrNy/gHl6pvw1j3ORomWg/5z3HHKvQsusGjgnIXtrD/OeZ4GIoFqeZ4T8Eh1DMyP0atJvveYsFDdltT3wMM+M8v7/qn7+58gf0nlSKfZ8rhQm+L0shjcHDWTxyMBUSUSDDAA3uKnqxO0FOowRyGK5a/yStvnW55bQ2W
    POSTGRES_PASSWORD: AgBd69gpNIjg+FUpDN0kVQCGGTC1N5nyYHwFgxHq49N/ckClWGaLoZyzchyd+94YFOwq3OUyCWj2AhJAq1gxVkyRs1iw53/sGwROmpj9FsBVAgPi3eTFNCn3Y8TGlmCIlkw7ilPQaDwqo68e7/iy8BIecVfoiAd0ehZAOL5hjGzOL9Eg27BO14/SNDlMqbpVb713jYUEgFt7VJooE1WTpntNvNwJsL/GIplAhOh9KhpjMSaE3C6/a/JGjOXrYpedwDZAvwIk0nVwy5nGDQmU7UXalQcRiq1lkVXEla7ffPTK4sPvk8umw5yNPtuxkZDiNUqUq6wX/0mEBbAIDaI7XcFHDL8bQm2L9GdtCsmOMcjo4n6zVtj4gyu4zmj4WLI79LmDuI3JpTbn5hMLBplBvfO3tFFypmP4AULwAj1r02G18HQB0VJgIK+Fs/JoCqq2K1eMbUbipKtNqBXVjfkmPL7dRbYv1zf2R1ftmgISkiaMMcJq+oErlE98RbLbWlp6ohRfwyWS7SQetorLVGGiRGKJVSePZ/Z8l6FmYdZLhNOhAwoKWRQYuMT0d5meS4ITOAJdAX7GpFtVneD8fXAOE0rcF2If2BCQLQwBemCjjfCm6E1lywXHnmQBiKlUcqQIlYVStwhRxxdFzMgMiua/BdBAfjResiTQMpnhgJCTD7Fqv650L5vE9tjeC/3cWggS0oUD8YxbnEdV47ae8nTKQ0AI91fJgyE6
  template:
    metadata:
      name: ai-pdf-secrets
      namespace: prod
