---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: app-studio-up
spec:
  encryptedData:
    .dockerconfigjson: AgBlB+m99aVKVoJ9E79ZppfZcg8cE+lKYxYH7aiHBQOKfWBVZ6PXSmEbPfTjgchygKPwD3/bKBHjkMDFMcIKPbeWWLY/GrNozZQp7lk11q8gFbc9WlWJ9v1o/CKj800xG1f1SQRCaeWgNV738u78P9Ni3C9dkk5m1sYmyvG8HIFqSIoUIV0reslvh0If2g3gy07xD15dtdpEByVjaL7j6wgbzZgU1zmPRkxYIek5IEiPDR51asg3S65AIsNCegA/MKxw6UDkK2WQyDH1RAN5DKFzvXelQislBlXC0va4feVW51Co7kQ4DIlMymmHOpuj20vEBafC2Gdkk866iMwHMeEzcinbQdu/ehCn0lesymMeGFfrm+7FZWkNBkKHOdK2ur8NPszXs80aq3BPxX8RBZuUhHDqYpCyG3ciF+c+Ioh0kBwtNaOSxnpvOLvejZGxV3AWHvt9KCErgc30gBmydscxNdowO2Nrk+O7ZliLXGK1rvMiZ0nnWc/EZK4tR/bWIut4gXNujkX0lhlJgziCY7DAUZ1H3StbKuNsuYgUIuQWsQiEY/7uSRZb625ZM3Z0nFNZHkb1nfzKbZ9jtG4kqtbPKxK/59v9tO1nGeUY+cSzz5rYIcLIgYYZU72epzn4ur0C8x3C4iOuMMKK1jsro/MkxJwgSd1aR1GZzXMskR1v38dQa6OkkvnISLEnBTIlRAWRoopA7yr9g/cWSyvyoFLEha0WeU9Axydooz6cycBXLSgbcviVMohJnGPoJhVYY0vVMFw5CaS1ITncaQx8iBz6+AXpAB1AOt+cAdmtnIHhcALAOU2N070ZX/fR2BOLeJXSymdOpQY8ZTe5yIqMQ1vcl4ECBjjBnNzQrE6dwk41QfDjDSylJ8Ro0TV/4dVz5a+6OEKXq3ZuyPqzzB2ciTbnTmwh5XerOGy+HXBy8v4nUnjF
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: app-studio-up
    type: kubernetes.io/dockerconfigjson
